[project]
name = "speaker-diarization-api"
version = "0.1.0"
description = "A FastAPI API for speaker diarization using AWS Transcribe."

requires-python = ">=3.9"

dependencies = [
    "boto3>=1.39.3",
]

[tool.uv]
dev-dependencies = [
    "pre-commit>=4.1.0",
    "ruff>=0.9.2",
]

[tool.hatch.build.targets.wheel]
packages = ["src/app", "src/infra"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
